<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CourseCategoryTableSeeder extends Seeder
{
    public function run(){
    \DB::table('course_category')->insert(array(
        array('id' => '1','company_id' => '1','branch_id' => NULL,'course_category_title' => 'Varsity Admission','course_category_slug' => NULL,'course_category_details' => '<p>Varsity Admission<br></p>','course_category_image' => '/upload/images/course_category_image/course_category_image_1.jpg','course_category_status' => 'ACTIVE','course_category_featured' => 'YES','course_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:34:19','updated_at' => '2021-10-24 12:34:19'),
        array('id' => '2','company_id' => '1','branch_id' => NULL,'course_category_title' => 'IELTS','course_category_slug' => NULL,'course_category_details' => '<p>IELTS<br></p>','course_category_image' => '/upload/images/course_category_image/course_category_image_2.jpg','course_category_status' => 'ACTIVE','course_category_featured' => 'YES','course_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:34:57','updated_at' => '2021-10-24 12:34:57'),
        array('id' => '3','company_id' => '1','branch_id' => NULL,'course_category_title' => 'Government Exam','course_category_slug' => NULL,'course_category_details' => '<p>Government Exam<br></p>','course_category_image' => '/upload/images/course_category_image/course_category_image_3.jpg','course_category_status' => 'ACTIVE','course_category_featured' => 'YES','course_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:35:24','updated_at' => '2021-10-24 12:35:24'),
        array('id' => '4','company_id' => '1','branch_id' => NULL,'course_category_title' => 'Academic','course_category_slug' => NULL,'course_category_details' => NULL,'course_category_image' => '/upload/images/course_category_image/course_category_image_4.jpg','course_category_status' => 'ACTIVE','course_category_featured' => 'YES','course_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:35:47','updated_at' => '2021-10-24 12:35:47')
    ));

    \DB::table('course_sub_category')->insert(array(
        array('id' => '1','company_id' => '1','branch_id' => NULL,'course_category_id' => '1','course_sub_category_title' => 'BBA','course_sub_category_slug' => NULL,'course_sub_category_details' => '<p>BBA<br></p>','course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_1.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:36:33','updated_at' => '2021-10-24 12:36:33'),
        array('id' => '2','company_id' => '1','branch_id' => NULL,'course_category_id' => '2','course_sub_category_title' => 'Spoken','course_sub_category_slug' => NULL,'course_sub_category_details' => '<p>Spoken<br></p>','course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_2.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:37:06','updated_at' => '2021-10-24 12:37:06'),
        array('id' => '3','company_id' => '1','branch_id' => NULL,'course_category_id' => '3','course_sub_category_title' => 'Bank Job','course_sub_category_slug' => NULL,'course_sub_category_details' => '<p>Bank Job<br></p>','course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_3.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:37:41','updated_at' => '2021-10-24 12:37:41'),
        array('id' => '4','company_id' => '1','branch_id' => NULL,'course_category_id' => '4','course_sub_category_title' => 'English','course_sub_category_slug' => NULL,'course_sub_category_details' => '<p>English<br></p>','course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_4.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:39:04','updated_at' => '2021-10-24 12:39:04'),
        array('id' => '5','company_id' => '1','branch_id' => NULL,'course_category_id' => '3','course_sub_category_title' => 'BCS Program','course_sub_category_slug' => NULL,'course_sub_category_details' => '<p>BCS Program<br></p>','course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_5.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:39:40','updated_at' => '2021-10-24 12:39:40'),
        array('id' => '6','company_id' => '1','branch_id' => NULL,'course_category_id' => '1','course_sub_category_title' => 'MBA','course_sub_category_slug' => NULL,'course_sub_category_details' => NULL,'course_sub_category_image' => '/upload/images/course_sub_category_image/course_sub_category_image_6.jpg','course_sub_category_status' => 'ACTIVE','course_sub_category_featured' => 'YES','course_sub_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:40:23','updated_at' => '2021-10-24 12:40:23')
    ));
      
    \DB::table('course_child_category')->insert(array(
        array('id' => '1','company_id' => '1','branch_id' => NULL,'course_category_id' => '1','course_sub_category_id' => '1','course_child_category_title' => 'Dhaka University','course_child_category_slug' => NULL,'course_child_category_details' => '<p>Dhaka University<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_1.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:41:17','updated_at' => '2021-10-24 12:41:17'),
        array('id' => '2','company_id' => '1','branch_id' => NULL,'course_category_id' => '2','course_sub_category_id' => '2','course_child_category_title' => 'Phonetics','course_child_category_slug' => NULL,'course_child_category_details' => '<p>Phonetics<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_2.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:41:46','updated_at' => '2021-10-24 12:41:46'),
        array('id' => '3','company_id' => '1','branch_id' => NULL,'course_category_id' => '3','course_sub_category_id' => '3','course_child_category_title' => 'SBI Exam','course_child_category_slug' => NULL,'course_child_category_details' => '<p>SBI Exam<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_3.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:42:34','updated_at' => '2021-10-24 12:42:34'),
        array('id' => '4','company_id' => '1','branch_id' => NULL,'course_category_id' => '4','course_sub_category_id' => '4','course_child_category_title' => 'Grammar','course_child_category_slug' => NULL,'course_child_category_details' => '<p>Grammar<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_4.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:43:32','updated_at' => '2021-10-24 12:43:32'),
        array('id' => '5','company_id' => '1','branch_id' => NULL,'course_category_id' => '3','course_sub_category_id' => '5','course_child_category_title' => 'BCS Preparation','course_child_category_slug' => NULL,'course_child_category_details' => '<p>BCS Preparation<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_5.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:45:02','updated_at' => '2021-10-24 12:45:02'),
        array('id' => '6','company_id' => '1','branch_id' => NULL,'course_category_id' => '1','course_sub_category_id' => '6','course_child_category_title' => 'Dhaka University','course_child_category_slug' => NULL,'course_child_category_details' => '<p>Dhaka University<br></p>','course_child_category_image' => '/upload/images/course_child_category_image/course_child_category_image_6.jpg','course_child_category_status' => 'ACTIVE','course_child_category_featured' => 'YES','course_child_category_position' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => NULL,'deleted_at' => NULL,'created_at' => '2021-10-24 12:46:34','updated_at' => '2021-10-24 12:46:34')
    ));
    }
}